apiVersion: apps/v1
kind: Deployment
metadata:
  name: whosay
  labels:
    app: whosay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whosay
  template:
    metadata:
      labels:
        app: whosay
    spec:
      containers:
      - name: whosay
        image: docker.io/parthtiwari/whosay:ff1c7b7
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        securityContext:
          privileged: true
        args: ["--all", "--watch"]
