apiVersion: v1
kind: Service
metadata:
  name: whosay
  labels:
    app: whosay
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: whosay
  type: ClusterIP
