name: CI Pipeline

# Defines when the workflow runs
on:
  # Triggered on push events to these branches
  push:
    branches: [ main, develop ]
  # Triggered on pull request events to these branches
  pull_request:
    branches: [ main, develop ]
  # Allow manual triggers from the Actions tab
  workflow_dispatch:

# Environment variables used across jobs
env:
  GO_VERSION: '1.20'
  IMAGE_NAME: parthtiwari/whosay
  REGISTRY: docker.io

# A workflow can have multiple jobs that run in parallel
jobs:
  # First job: Build and test the Go application
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        # This action checks out your repository so the workflow can access it
      
      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          # This sets up the specified Go version
          
      # Step 3: Cache Go modules to speed up subsequent runs
      - name: Go module cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            # Cache key is based on go.sum file hash
      
      # Step 4: Download Go dependencies
      - name: Download dependencies
        run: go mod download
        # Downloads all dependencies declared in go.mod
      
      # Step 5: Verify dependencies 
      - name: Verify dependencies
        run: go mod verify
        # Verifies that dependencies have not been modified since being downloaded
      
      # Step 6: Run static code analysis tools
      - name: Run go vet
        run: go vet ./...
        # Examines Go source code and reports suspicious constructs
      
      # Step 7: Run tests with coverage
      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        continue-on-error: true
        # Runs all tests with race detector and generates coverage report
      
      # Step 8: Upload coverage report
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
        continue-on-error: true
          # Uploads the coverage report to Codecov for visualization
      
      # Step 9: Build binary to ensure compilation works
      - name: Build
        run: go build -v ./...
        # Builds the application to verify it compiles correctly

  # Second job: Build and push Docker image (only on main branch or tags)
  docker-build-push:
    name: Build and Push Docker Image
    needs: build-test
    runs-on: ubuntu-latest
    # This job only runs if build-test is successful
    if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    
    steps:
      # Step 1: Check out the repository again for this job
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # Sets up Docker Buildx for efficient multi-platform image building
      
      # Step 3: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Uses stored secrets for authentication
      
      # Step 4: Set up image tag
      - name: Set up image tag
        id: tag
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF#refs/tags/},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
            echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi
      
      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ env.VERSION }}
          # Builds and pushes the Docker image with the determined tags
      
      # Step 6: Update deployment manifest
      - name: Update deployment manifest
        run: |
          sed -i "s|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(git rev-parse --short HEAD)|" ./k8s/deployment.yaml
          cat ./k8s/deployment.yaml
          # Updates the Kubernetes manifest with the new version
      
      # Step 7: Commit and push updated manifest
      - name: Commit and push updated manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update deployment to use image $(git rev-parse --short HEAD)"
          file_pattern: "./k8s/deployment.yaml"
          # Commits the updated manifest back to the repository
